package configproxy

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
)

type Endpoint struct {
	Host string
	Port int
}

func (endpoint Endpoint) Valid() bool {
	return endpoint.Host != "" && endpoint.Port > 0 && endpoint.Port <= 65535
}

type RewriteOptions struct {
	LocalHost string
	LocalPort int
	Affinity  string
}

func Rewrite(content []byte, options RewriteOptions) ([]byte, Endpoint, error) {
	if options.LocalHost == "" || options.LocalPort <= 0 || options.LocalPort > 65535 {
		return nil, Endpoint{}, fmt.Errorf("invalid local proxy endpoint %q:%d", options.LocalHost, options.LocalPort)
	}
	var config map[string]any
	if err := json.Unmarshal(content, &config); err != nil {
		return nil, Endpoint{}, fmt.Errorf("decode client config: %w", err)
	}
	endpoint := Endpoint{}
	if host, ok := config["chat.host"].(string); ok {
		endpoint.Host = host
	}
	if port, ok := jsonNumberToInt(config["chat.port"]); ok {
		endpoint.Port = port
	}
	if affinities, ok := config["chat.affinities"].(map[string]any); ok {
		if options.Affinity != "" {
			if host, ok := affinities[options.Affinity].(string); ok && host != "" {
				endpoint.Host = host
			}
		}
	}
	if !endpoint.Valid() {
		return append([]byte(nil), content...), Endpoint{}, nil
	}
	config["chat.host"] = options.LocalHost
	config["chat.port"] = options.LocalPort
	// Riot's chat service supports an explicit local-proxy mode. The proxy
	// certificate is generated by RiftOps for 127.0.0.1, so no external CA,
	// predecessor hostname, or downloaded certificate is required.
	config["chat.allow_bad_cert.enabled"] = true
	if affinities, ok := config["chat.affinities"].(map[string]any); ok {
		for key := range affinities {
			affinities[key] = options.LocalHost
		}
	}
	modified, err := json.Marshal(config)
	if err != nil {
		return nil, Endpoint{}, fmt.Errorf("encode client config: %w", err)
	}
	return modified, endpoint, nil
}

func AffinityFromJWT(token string) (string, error) {
	parts := strings.Split(token, ".")
	if len(parts) < 2 {
		return "", fmt.Errorf("token has %d segments", len(parts))
	}
	payload, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return "", fmt.Errorf("decode token payload: %w", err)
	}
	var claims struct {
		Affinity string `json:"affinity"`
	}
	if err := json.Unmarshal(payload, &claims); err != nil {
		return "", fmt.Errorf("decode token claims: %w", err)
	}
	if claims.Affinity == "" {
		return "", fmt.Errorf("token contains no affinity")
	}
	return claims.Affinity, nil
}

func jsonNumberToInt(value any) (int, bool) {
	switch number := value.(type) {
	case float64:
		if number <= 0 || number > 65535 || number != float64(int(number)) {
			return 0, false
		}
		return int(number), true
	case json.Number:
		parsed, err := number.Int64()
		return int(parsed), err == nil && parsed > 0 && parsed <= 65535
	default:
		return 0, false
	}
}
